name: Daily Commit

on:
  schedule:
    - cron: '28 16 * * *'  # Runs daily at 10:28 PM IST
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update timestamp - 23f1001411@ds.study.iitm.ac.in
        run: |
          echo "Last updated at $(date -u)" > daily-update.txt
          git config user.name "GitHub Action Bot"
          git config user.email "23f1001411@ds.study.iitm.ac.in"
          git add daily-update.txt
          git commit -m "Daily update: $(date -u)" || echo "No changes to commit"
      
      - name: Push changes
        run: |
          git push origin HEAD:${{ github.ref_name }}
